### ISSUE TITLE
Search for a product by name or description

### ISSUE THREAD

**Issue by cloki0610** [cloki0610/boutique_ado_Walkthrough#14]
As a Shopper,
I want to be able to search for a product by name or description,
so that I can find a specific product I'd like to purchase.

**Comment by Abhishek-1337** [comment]
@cloki0610 Hey , I am new to this community exploring things for any little contribution needed.
I just want to start with good beginner issues. Is this a open issue where I can contribute?

**Comment by cloki0610** [comment]
> @cloki0610 Hey , I am new to this community exploring things for any little contribution needed. I just want to start with good beginner issues. Is this a open issue where I can contribute?

Oops, I'm just discovering GitHub's label feature with this walk-through project.
This is course material for personal study so it is not an issue that needs to be solved.
And these issues are created for learning project management.
Everything will be complete in the following few days.
I'm so sorry for this misleading.

**Comment by Abhishek-1337** [comment]
Ohhh! My bad i guess.
Thanks for your kind response.
